FROM python:3.14-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /migrations
COPY requirements.txt ./
RUN pip install --no-cache-dir --requirement requirements.txt
COPY . .
ENTRYPOINT ["python", "migrate.py"]

